<a href="https://colab.research.google.com/github/miladziekanowska/stock-market-forecast-project/blob/main/DJ30stocks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Instaled yahoo finance and frameworks

In [ ]:
pip install Yahoo_fin

In [19]:
import pandas as pd
import numpy as np
import yahoo_fin.stock_info as yh

In [5]:
df = yh.tickers_nasdaq()

In [ ]:
df

Made a dictionary that contains informations about Dow Jones stocks

In [ ]:
ticker_list = yh.tickers_dow()
historical_datas = {}
for ticker in ticker_list:
    historical_datas[ticker] = yh.get_data(ticker, start_date="13/07/1993", end_date="12/07/2023", index_as_date = False, interval="1d")

In [34]:
len(historical_datas)

30

In [39]:
yh.tickers_dow()

['AAPL',
 'AMGN',
 'AXP',
 'BA',
 'CAT',
 'CRM',
 'CSCO',
 'CVX',
 'DIS',
 'DOW',
 'GS',
 'HD',
 'HON',
 'IBM',
 'INTC',
 'JNJ',
 'JPM',
 'KO',
 'MCD',
 'MMM',
 'MRK',
 'MSFT',
 'NKE',
 'PG',
 'TRV',
 'UNH',
 'V',
 'VZ',
 'WBA',
 'WMT']

In [25]:
historical_datas['AAPL']

,date,open,high,low,close,adjclose,volume,ticker
0,1993-07-13,0.345982,0.345982,0.330357,0.332589,0.273418,158110400,AAPL
1,1993-07-14,0.328125,0.334821,0.319196,0.332589,0.273418,246299200,AAPL
2,1993-07-15,0.332589,0.337054,0.314732,0.319196,0.262408,338038400,AAPL
3,1993-07-16,0.254464,0.264509,0.236607,0.245536,0.201853,2120596800,AAPL
4,1993-07-19,0.250000,0.256696,0.227679,0.228795,0.188090,806232000,AAPL
...,...,...,...,...,...,...,...,...
7550,2023-07-07,191.410004,192.669998,190.240005,190.679993,190.679993,46778000,AAPL
7551,2023-07-10,189.259995,189.990005,187.039993,188.610001,188.610001,59922200,AAPL
7552,2023-07-11,189.160004,189.300003,186.600006,188.080002,188.080002,46638100,AAPL
7553,2023-07-12,189.679993,191.699997,188.470001,189.770004,189.770004,60690100,AAPL
7554,2023-07-13,190.500000,191.095001,189.779999,190.425003,190.425003,20368468,AAPL

Percentage of change during day counted

In [30]:
for key in historical_datas:
  historical_datas[key]['%changed'] = historical_datas[key].apply(lambda x: ((x[4] - x[1])/x[1] * 100), axis = 1)

In [33]:
historical_datas['MSFT']

,date,open,high,low,close,adjclose,volume,ticker,%changed
0,1993-07-13,2.625000,2.625000,2.578125,2.585938,1.609843,36476800,MSFT,-1.488077
1,1993-07-14,2.593750,2.671875,2.578125,2.632813,1.639024,43491200,MSFT,1.506042
2,1993-07-15,2.632813,2.632813,2.585938,2.609375,1.624434,34432000,MSFT,-0.890226
3,1993-07-16,2.601563,2.601563,2.523438,2.535156,1.578230,86217600,MSFT,-2.552580
4,1993-07-19,2.484375,2.507813,2.437500,2.460938,1.532026,122435200,MSFT,-0.943377
...,...,...,...,...,...,...,...,...,...
7550,2023-07-07,339.320007,341.790009,337.000000,337.220001,337.220001,21185300,MSFT,-0.618887
7551,2023-07-10,334.600006,335.230011,327.589996,331.829987,331.829987,32791400,MSFT,-0.827860
7552,2023-07-11,331.059998,332.859985,327.000000,332.470001,332.470001,26698200,MSFT,0.425906
7553,2023-07-12,336.600006,341.649994,335.670013,337.200012,337.200012,29965300,MSFT,0.178255
7554,2023-07-13,339.559998,342.470001,339.019989,340.978088,340.978088,10917681,MSFT,0.417626

Chcked if any columns contains NaN value

In [ ]:
for key in historical_datas:
  historical_datas[key].isna().info()